project:
  type: website
  preview:
    port: 3000
    browser: false

format:
  html:
    theme:
        light: flatly
        dark: darkly
    css: styles.css
    toc: true
    toc-depth: 4

website:
  twitter-card: true
  title: "Billy's Page"
  open-graph: false
  repo-actions: [issue]
  favicon: images/forest.png
  sidebar:
      style: floating
      contents:
        - auto: "/*.ipynb"
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Projects"
        href: My_pojects.html
      - text: "Resume"
        href: images/CV.pdf
      - text: "Contact"
        menu:
          - icon: envelope
            text: afterhoursbilly@gmail.com
            href: mailto:afterhoursbilly@gmail.com
          - icon: discord
            text: b1x4#9406
            href: https://www.discord.com/users/1063240042291671050
    right:
      - icon: github
        href: "https://github.com/GalaxUniv"
      - icon: twitter
        href: https://twitter.com/afterhoursbilly

metadata-files: [nbdev.yml]

