project:
  type: website
  preview:
    port: 3000
    browser: false

format:
  html:
    theme:
        light: flatly
        dark: darkly
    css: styles.css
    toc: true
    toc-depth: 4

website:
  twitter-card: true
  title: "Billy's Page"
  open-graph: false
  repo-actions: [issue]
  favicon: images/forest.png
  sidebar:
      style: floating
      contents:
        - auto: "/*.ipynb"
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Projects"
        href: My_pojects.html
      - text: "Resume"
        href: images/cv.pdf
    right:
      - icon: github
        href: "https://github.com/GalaxUniv"
      - icon: twitter
        href: https://twitter.com/afterhoursbilly

metadata-files: [nbdev.yml]

