project:
  type: website
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  twitter-card: true
  open-graph: false
  repo-actions: [issue]
  sidebar:
    style: floating
    contents:
      - auto: "/*.ipynb"
  favicon: favicon.png
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "idk"
        href: getting_started.ipynb
      - text: "Projects"
        href: My_pojects.html
      - text: "Curriculum vitae"
        href: images/cv.pdf
      - text: "Contact"
        menu:
          - text: "Discord"
            icon: discord
            href: https://github.com/fastai/nbdev/issues
          - text: "Email"
            icon: envelope-fill
            href: https://forums.fast.ai/
          - text: "C"
            icon: question-circle
            href: getting_started.ipynb#faq
    right:
      - icon: github
        href: "https://github.com/GalaxUniv"
      - icon: twitter
        href: https://twitter.com/afterhoursbilly

metadata-files: [nbdev.yml]

