# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Page',
                'doc_host': 'https://GalaxUniv.github.io',
                'git_url': 'https://github.com/GalaxUniv/Page',
                'lib_path': 'Page'},
  'syms': { 'Page.core': {'Page.core.Core': ('core.html#core', 'Page/core.py')},
            'Page.projects_l': {'Page.projects_l.projects': ('projects.html#projects', 'Page/projects_l.py')}}}
