# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Page',
                'doc_host': 'https://GalaxUniv.github.io',
                'git_url': 'https://github.com/GalaxUniv/Page',
                'lib_path': 'Page'},
  'syms': {'Page.core': {'Page.core.foo': ('core.html#foo', 'Page/core.py')}}}
